# This is a basic workflow to help you get started with Actions

name: CI

on:
  push:
    branches: [main]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: checkout release
        uses: actions/checkout@v3

      - name: compress
        run: tar cvfz ./$GITHUB_SHA.tar.gz *
        shell: bash

      - name: AWS configure credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
          aws-region: ap-northeast-2

      - name: upload to S3
        run: aws s3 cp --region ap-northeast-2 ./$GITHUB_SHA.tar.gz s3://[phedy-codedeploy-bucket]

      - name: deploy with AWS codeDeploy
        run: aws deploy create-deployment
          --application-name [phedy-codedeply-app]
          --deployment-config-name CodeDeployDefault.OneAtATime
          --deployment-group-name [phedy-codedeploy-group]
          --s3-location bucket=phedy-codedeploy-bucket,bundleType=tgz,key=$GITHUB_SHA.tar.gz
